INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (394944, 10, 1, 'malo', 'Bariloche');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (147271, 7, 2, 'muy bueno', 'Parana');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (301254, 6, 3, 'muy bueno', 'Santa Fe');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (73433, 11, 4, 'muy bueno', 'Gualeguay');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (112032, 2, 5, 'regular', 'Bahia Blanca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (153066, 6, 6, 'bueno', 'Monteros');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (446186, 7, 7, 'malo', 'Federeacion');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (213586, 9, 8, 'muy bueno', 'Bariloche');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (465276, 5, 9, 'malo', 'Rafaela');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (198806, 2, 10, 'muy bueno', 'Villa la angostura');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (171331, 8, 11, 'malo', 'Cutral Co');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (460119, 5, 12, 'malo', 'Gualeguaychu');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (401710, 4, 13, 'regular', 'Godoy Cruz');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (374084, 10, 14, 'muy bueno', 'Gualeguay');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (332224, 9, 15, 'malo', 'Cosquin');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (471471, 4, 16, 'muy bueno', 'Gualeguaychu');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (294136, 1, 17, 'regular', 'Parana');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (186808, 8, 18, 'muy bueno', 'Parana');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (439113, 4, 19, 'bueno', 'Villa la angostura');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (485934, 5, 20, 'bueno', 'Concepcion');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (186842, 12, 21, 'regular', 'Gualeguay');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (255402, 12, 22, 'malo', 'Mendoza');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (498248, 4, 23, 'malo', 'Neuquen');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (438033, 10, 24, 'regular', 'Concepcion');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (235164, 5, 25, 'regular', 'Rosario');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (344252, 6, 26, 'malo', 'Capilla del monte');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (124490, 1, 27, 'muy bueno', 'Santa Fe');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (291294, 12, 28, 'bueno', 'Rosario');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (71426, 9, 29, 'bueno', 'San Martin de los Andes');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (451860, 11, 30, 'muy bueno', 'Rosario');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (78809, 2, 31, 'malo', 'Bahia Blanca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (388091, 3, 32, 'muy bueno', 'Cordoba');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (52710, 3, 33, 'malo', 'Monteros');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (150660, 4, 34, 'malo', 'Federeacion');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (42347, 4, 35, 'malo', 'Simoca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (289132, 7, 36, 'muy bueno', 'Santa Fe');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (54113, 2, 37, 'bueno', 'Maipu');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (146024, 5, 38, 'regular', 'Parana');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (416164, 10, 39, 'muy bueno', 'Maipu');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (217789, 12, 40, 'muy bueno', 'Capilla del monte');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (382698, 4, 41, 'regular', 'Gualeguaychu');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (398437, 12, 42, 'bueno', 'Cosquin');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (113278, 8, 43, 'regular', 'Mendoza');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (431763, 7, 44, 'muy bueno', 'Rafaela');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (160206, 10, 45, 'muy bueno', 'Rafaela');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (468733, 4, 46, 'bueno', 'Santa Fe');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (418106, 12, 47, 'muy bueno', 'Cordoba');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (319221, 4, 48, 'malo', 'Simoca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (355890, 7, 49, 'regular', 'Gualeguay');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (124620, 8, 50, 'bueno', 'Godoy Cruz');
