INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (33370, 12, 1, "malo", Santa Fe);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (218190, 5, 2, "malo", La plata);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (111298, 11, 3, "bueno", San Martin de los Andes);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (188617, 6, 4, "regular", Cosquin);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (324274, 5, 5, "muy bueno", Cosquin);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (357751, 6, 6, "regular", Capilla del monte);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (186326, 11, 7, "muy bueno", Capilla del monte);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (239269, 11, 8, "malo", San Martin de los Andes);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (328179, 3, 9, "regular", Mendoza);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (353489, 9, 10, "malo", Godoy Cruz);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (232947, 9, 11, "malo", Maipu);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (213363, 1, 12, "bueno", Mar del plata);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (31924, 5, 13, "malo", Bariloche);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (410756, 7, 14, "regular", Rivadavia);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (209487, 3, 15, "regular", Concepcion);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (227628, 8, 16, "malo", Villa la angostura);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (301326, 8, 17, "malo", Rafaela);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (469830, 10, 18, "regular", Capilla del monte);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (119241, 2, 19, "muy bueno", Capilla del monte);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (483220, 8, 20, "muy bueno", Ciudad de Yerba Buena);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (13200, 2, 21, "bueno", Rosario);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (389252, 11, 22, "bueno", Gualeguay);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (226706, 4, 23, "bueno", Santa Fe);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (313969, 6, 24, "regular", Godoy Cruz);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (370123, 1, 25, "malo", Parana);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (473776, 6, 26, "regular", Rafaela);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (260716, 2, 27, "bueno", Ciudad de Yerba Buena);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (445782, 6, 28, "regular", San Martin de los Andes);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (114981, 10, 29, "malo", Rosario);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (318215, 7, 30, "malo", Bariloche);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (252860, 9, 31, "bueno", Cordoba);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (436350, 11, 32, "malo", Gualeguay);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (210684, 12, 33, "malo", Simoca);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (337139, 3, 34, "malo", Monteros);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (201927, 10, 35, "regular", Cordoba);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (486626, 4, 36, "muy bueno", Rosario);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (461682, 6, 37, "muy bueno", Esperanza);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (154118, 2, 38, "regular", Rivadavia);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (448237, 12, 39, "malo", Federeacion);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (150843, 4, 40, "muy bueno", Mar del plata);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (77490, 2, 41, "muy bueno", Buenos Aires);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (472894, 10, 42, "malo", Cutral Co);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (282418, 5, 43, "malo", Gualeguaychu);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (376995, 9, 44, "muy bueno", Godoy Cruz);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (64424, 8, 45, "muy bueno", Monteros);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (331250, 6, 46, "muy bueno", Carlos Paz);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (228802, 11, 47, "malo", Esperanza);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (479515, 7, 48, "malo", Gualeguaychu);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (113627, 9, 49, "muy bueno", Rosario);
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (204955, 9, 50, "bueno", La plata);
