INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (250629, 8, 1, 'malo', 'Cutral Co');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (126069, 4, 2, 'bueno', 'Cutral Co');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (354148, 7, 3, 'regular', 'Mendoza');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (295240, 2, 4, 'regular', 'Esperanza');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (288595, 9, 5, 'muy bueno', 'Esperanza');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (472659, 8, 6, 'bueno', 'Concepcion');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (46942, 4, 7, 'muy bueno', 'Neuquen');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (268842, 9, 8, 'bueno', 'Bahia Blanca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (493375, 6, 9, 'malo', 'Ciudad de Yerba Buena');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (301467, 2, 10, 'muy bueno', 'La plata');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (406374, 5, 11, 'muy bueno', 'Rivadavia');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (377659, 9, 12, 'malo', 'Neuquen');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (419384, 7, 13, 'bueno', 'Maipu');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (334819, 11, 14, 'bueno', 'Ciudad de Yerba Buena');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (13818, 4, 15, 'malo', 'Capilla del monte');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (390607, 2, 16, 'bueno', 'Buenos Aires');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (74759, 8, 17, 'bueno', 'Godoy Cruz');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (209540, 8, 18, 'malo', 'Cutral Co');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (315935, 12, 19, 'malo', 'Federeacion');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (161524, 11, 20, 'regular', 'Simoca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (222455, 2, 21, 'malo', 'San Martin de los Andes');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (106210, 9, 22, 'muy bueno', 'Simoca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (244864, 10, 23, 'muy bueno', 'Esperanza');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (483769, 12, 24, 'bueno', 'Cosquin');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (259669, 6, 25, 'muy bueno', 'Neuquen');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (466561, 4, 26, 'muy bueno', 'Parana');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (279355, 6, 27, 'bueno', 'Mendoza');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (140223, 1, 28, 'regular', 'San Martin de los Andes');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (361980, 6, 29, 'regular', 'Bahia Blanca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (33625, 10, 30, 'malo', 'Rosario');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (48986, 9, 31, 'regular', 'Concepcion');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (444730, 5, 32, 'regular', 'Godoy Cruz');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (469503, 8, 33, 'bueno', 'Federeacion');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (220351, 3, 34, 'muy bueno', 'La plata');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (96821, 1, 35, 'bueno', 'Rafaela');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (50942, 2, 36, 'muy bueno', 'Rivadavia');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (347387, 7, 37, 'regular', 'Neuquen');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (433046, 4, 38, 'regular', 'Mendoza');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (157509, 8, 39, 'regular', 'Bahia Blanca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (426611, 8, 40, 'regular', 'Parana');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (106327, 2, 41, 'bueno', 'Godoy Cruz');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (271725, 10, 42, 'regular', 'San Martin de los Andes');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (383831, 8, 43, 'bueno', 'Bahia Blanca');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (253690, 8, 44, 'malo', 'Cosquin');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (414864, 6, 45, 'malo', 'Esperanza');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (136191, 6, 46, 'muy bueno', 'Rosario');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (54157, 11, 47, 'regular', 'Mar del plata');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (168452, 1, 48, 'muy bueno', 'Federeacion');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (425467, 1, 49, 'bueno', 'Rivadavia');
INSERT INTO Ciudades (Poblacion, Id_depto, Id_ciudad, Clasificacion, Nom_ciudad) VALUES (354762, 5, 50, 'muy bueno', 'Rafaela');
